// const verbs = [
//     { base: "be", past: "was/were", participle: "been", translation: "бути" },
//     { base: "become", past: "became", participle: "become", translation: "ставати" },
//     { base: "begin", past: "began", participle: "begun", translation: "починати" },
//     { base: "break", past: "broke", participle: "broken", translation: "ламати" },
//     { base: "bring", past: "brought", participle: "brought", translation: "приносити" },
//     { base: "build", past: "built", participle: "built", translation: "будувати" },
//     { base: "buy", past: "bought", participle: "bought", translation: "купувати" },
//     { base: "catch", past: "caught", participle: "caught", translation: "ловити" },
//     { base: "choose", past: "chose", participle: "chosen", translation: "вибирати" },
//     { base: "come", past: "came", participle: "come", translation: "приходити" },
//     { base: "cost", past: "cost", participle: "cost", translation: "коштувати" },
//     { base: "cut", past: "cut", participle: "cut", translation: "різати" },
//     { base: "do", past: "did", participle: "done", translation: "робити" },
//     { base: "draw", past: "drew", participle: "drawn", translation: "малювати" },
//     { base: "drink", past: "drank", participle: "drunk", translation: "пити" },
//     { base: "drive", past: "drove", participle: "driven", translation: "водити" },
//     { base: "eat", past: "ate", participle: "eaten", translation: "їсти" },
//     { base: "fall", past: "fell", participle: "fallen", translation: "падати" },
//     { base: "feel", past: "felt", participle: "felt", translation: "відчувати" },
//     { base: "find", past: "found", participle: "found", translation: "знаходити" },
//     { base: "fly", past: "flew", participle: "flown", translation: "літати" },
//     { base: "forget", past: "forgot", participle: "forgotten", translation: "забувати" },
//     { base: "forgive", past: "forgave", participle: "forgiven", translation: "прощати" },
//     { base: "freeze", past: "froze", participle: "frozen", translation: "замерзати" },
//     { base: "get", past: "got", participle: "got/gotten", translation: "отримувати" },
//     { base: "give", past: "gave", participle: "given", translation: "давати" },
//     { base: "go", past: "went", participle: "gone", translation: "йти" },
//     { base: "grow", past: "grew", participle: "grown", translation: "рости" },
//     { base: "have", past: "had", participle: "had", translation: "мати" },
//     { base: "hear", past: "heard", participle: "heard", translation: "чути" },
//     { base: "know", past: "knew", participle: "known", translation: "знати" }
// ];
const verbs = [
    { base: "be", past: "was/were", participle: "been", translation: "бути" },
    { base: "become", past: "became", participle: "become", translation: "ставати" },
    { base: "begin", past: "began", participle: "begun", translation: "починати" },
    { base: "break", past: "broke", participle: "broken", translation: "ламати" },
    { base: "bring", past: "brought", participle: "brought", translation: "приносити" },
    { base: "build", past: "built", participle: "built", translation: "будувати" },
    { base: "abide", past: "abode / abided", participle: "abode / abided", translation: "терпіти; дотримуватися чогось, бути вірним" },
    { base: "arise", past: "arose", participle: "arisen", translation: "виникати, підніматися" },
    { base: "awake", past: "awaked / awoke", participle: "awaked / awoken", translation: "будити, викликати, прокидатися, розуміти" },
    { base: "backslide", past: "backslid", participle: "backslidden / backslid", translation: "відступатися від віри, знову вдаватися до пороку" },
    { base: "bear", past: "bore / beared", participle: "born / borne / beared", translation: "нести, виносити, тримати, мати почуття" },
    { base: "beat", past: "beat", participle: "beaten / beat", translation: "бити, перемагати" },
    { base: "befall", past: "befell", participle: "befallen", translation: "траплятися, видаватися, випадати на долю" },
    { base: "behold", past: "beheld", participle: "beheld", translation: "побачити, помітити, споглядати, спостерігати" },
    { base: "bend", past: "bent", participle: "bent", translation: "гнути, згинати" },
    { base: "bereave", past: "bereft / bereaved", participle: "bereft / bereaved", translation: "позбавляти, віднімати, відбирати" },
    { base: "beseech", past: "besought / beseeched", participle: "besought / beseeched", translation: "просити, благати" },
    { base: "beset", past: "beset", participle: "beset", translation: "оточувати, осаджувати, перегороджувати" },
    { base: "bet", past: "bet / betted", participle: "bet / betted", translation: "битися об заклад, бути впевненим" },
    { base: "bid", past: "bid / bade", participle: "bidden", translation: "запрошувати, вітати, прощатися" },
    { base: "bide", past: "bode / bided", participle: "bided", translation: "вичікувати, терпіти, проживати, знаходитися" },
    { base: "bind", past: "bound", participle: "bound", translation: "зв'язувати, пов'язувати, скріплювати" },
    { base: "bite", past: "bit", participle: "bitten", translation: "кусати, клювати, жалити" },
    { base: "bleed", past: "bled", participle: "bled", translation: "кровоточити, спливати кров'ю" },
    { base: "bless", past: "blessed / blest", participle: "blessed / blest", translation: "благословляти, освячувати, перехрестити" },
    { base: "blow", past: "blew", participle: "blown", translation: "дути, видувати, віяти, вибухати" },
    { base: "breed", past: "bred", participle: "bred", translation: "розводити, виховувати, розмножуватися, плодитися" },
    { base: "broadcast", past: "broadcast / broadcasted", participle: "broadcast / broadcasted", translation: "віщати, поширювати, передавати по радіо / телебаченню" },
    { base: "burn", past: "burned / burnt", participle: "burned / burnt", translation: "горіти, спалювати" },
    { base: "burst", past: "burst", participle: "burst", translation: "вибухати, розриватися, виникати, бути переповненим" },
    { base: "bust", past: "busted / bust", participle: "busted / bust", translation: "зламати, руйнувати, розоритися, бити" },
    { base: "buy", past: "bought", participle: "bought", translation: "купувати" },
    { base: "cast", past: "cast", participle: "cast", translation: "кидати, відкидати, звільнити, відливати метал" },
    { base: "catch", past: "caught", participle: "caught", translation: "зловити, ловити, наздогнати" },
    { base: "chide", past: "chided / chid", participle: "chided / chid / chidden", translation: "сварити, дорікати, бурчати, ревіти" },
    { base: "choose", past: "chose", participle: "chosen", translation: "вибирати" },
    { base: "cleave", past: "cleft / clove", participle: "cleft / cloven", translation: "розколювати, розсікати" },
    { base: "cling", past: "clung", participle: "clung", translation: "чіплятися, триматися, липнути" },
    { base: "clothe", past: "clothed / clad", participle: "clothed / clad", translation: "одягнути, одягати, висловлювати, обдаровувати" },
    { base: "come", past: "came", participle: "come", translation: "приходити" },
    { base: "cost", past: "cost", participle: "cost", translation: "оцінювати, коштувати" },
    { base: "creep", past: "crept", participle: "crept", translation: "повзати, крастися, охоплювати, наводити жах" },
    { base: "crossbreed", past: "crossbred", participle: "crossbred", translation: "схрещувати" },
    { base: "cut", past: "cut", participle: "cut", translation: "різати, обрізати" },
    { base: "dare", past: "durst / dared", participle: "dared", translation: "сміти, кидати виклик, ризикувати" },
    { base: "daydream", past: "daydreamed / daydreamt", participle: "daydreamed / daydreamt", translation: "марити, мріяти, фантазувати" },
    { base: "deal", past: "dealt", participle: "dealt", translation: "мати справу, торгувати, розглядати питання" },
    { base: "dig", past: "dug", participle: "dug", translation: "копати, рити, шукати" },
    { base: "disprove", past: "disproved", participle: "disproved / disproven", translation: "спростовувати, доводити хибність" },
    { base: "dive", past: "dove / dived", participle: "dived", translation: "пірнати, стрибати вниз, занурюватися" },
    { base: "do", past: "did", participle: "done", translation: "робити, виконувати" },
    { base: "draw", past: "drew", participle: "drawn", translation: "креслити, малювати, уявляти; тягти, волочити" },
    { base: "dream", past: "dreamed / dreamt", participle: "dreamed / dreamt", translation: "бачити сни, мріяти" },
    { base: "drink", past: "drank", participle: "drunk", translation: "пити, випивати" },
    { base: "drive", past: "drove", participle: "driven", translation: "водити (машину), управляти, їздити" },
    { base: "dwell", past: "dwelt / dwelled", participle: "dwelt / dwelled", translation: "жити, мешкати, перебувати, зупинятися (десь)" },
    { base: "eat", past: "ate", participle: "eaten", translation: "їсти, харчуватися, роз'їдати" },
    { base: "fall", past: "fell", participle: "fallen", translation: "падати, опадати, опускатися" },
    { base: "feed", past: "fed", participle: "fed", translation: "годувати" },
    { base: "feel", past: "felt", participle: "felt", translation: "відчувати" },
    { base: "fight", past: "fought", participle: "fought", translation: "боротися, битися" },
    { base: "find", past: "found", participle: "found", translation: "знаходити, натрапити, виявляти" },
    { base: "fit", past: "fitted / fit", participle: "fitted / fit", translation: "підганяти, прилаштовувати, пристосовувати, оснащувати" },
    { base: "flee", past: "fled", participle: "fled", translation: "бігти, тікати, рятуватися втечею" },
    { base: "fling", past: "flung", participle: "flung", translation: "кидати, кидати" },
    { base: "fly", past: "flew", participle: "flown", translation: "літати, пролітати" },
    { base: "forbear", past: "forbore", participle: "forborne", translation: "утримуватися, терпіти, переносити" },
    { base: "forbid", past: "forbade", participle: "forbidden", translation: "забороняти" },
    { base: "forecast", past: "forecast", participle: "forecast", translation: "прогнозувати, передбачати" },
    { base: "forego", past: "forewent", participle: "foregone", translation: "передувати, йти попереду" },
    { base: "foresee", past: "foresaw", participle: "foreseen", translation: "передбачати, знати заздалегідь" },
    { base: "foretell", past: "foretold", participle: "foretold", translation: "передбачати, прогнозувати" },
    { base: "forget", past: "forgot", participle: "forgotten", translation: "забувати" },
    { base: "forgive", past: "forgave", participle: "forgiven", translation: "прощати" },
    { base: "forgo", past: "forwent", participle: "forgone", translation: "відмовлятися, утримуватися" },
    { base: "forsake", past: "forsook", participle: "forsaken", translation: "кидати, залишати, відмовлятися" },
    { base: "forswear", past: "forswore", participle: "forsworn", translation: "зрікатися, відмовлятися, відкидати" },
    { base: "freeze", past: "froze", participle: "frozen", translation: "замерзати, заморожувати" },
    { base: "frostbite", past: "frostbit", participle: "frostbitten", translation: "обморозити, відморозити" },
    { base: "get", past: "got", participle: "got/gotten", translation: "отримувати, ставати" },
    { base: "gild", past: "gilded / gilt", participle: "gilded / gilt", translation: "золотити, покривати позолотою, прикрашати" },
    { base: "give", past: "gave", participle: "given", translation: "давати" },
    { base: "go", past: "went", participle: "gone", translation: "йти, їхати" },
    { base: "grind", past: "ground", participle: "ground", translation: "молоти, розтерти, шліфувати, точити" },
    { base: "grow", past: "grew", participle: "grown", translation: "рости, вирощувати" },
    { base: "hand-feed", past: "hand-fed", participle: "hand-fed", translation: "годувати, давати з рук" },
    { base: "handwrite", past: "handwrote", participle: "handwritten", translation: "писати від руки" },
    { base: "hang", past: "hung", participle: "hung", translation: "висіти, вішати" },
    { base: "have", past: "had", participle: "had", translation: "мати, володіти" },
    { base: "hear", past: "heard", participle: "heard", translation: "чути, слухати" },
    { base: "heave", past: "heaved / hove", participle: "heaved / hove", translation: "піднімати, кидати, рухати, випускати, здійматися" },
    { base: "hew", past: "hewed", participle: "hewn / hewed", translation: "рубати, тесати, відбувати, узгоджуватися, дотримуватися" },
    { base: "hide", past: "hid", participle: "hidden", translation: "ховати, ховатися" },
    { base: "hit", past: "hit", participle: "hit", translation: "ударяти, вражати, попадати" },
    { base: "hold", past: "held", participle: "held", translation: "займати, тримати, утримувати" },
    { base: "hurt", past: "hurt", participle: "hurt", translation: "пошкодити, заподіювати біль, кривдити, поранити" },
    { base: "inbreed", past: "inbred", participle: "inbred", translation: "вирощувати, виховувати щось в когось" },
    { base: "inlay", past: "inlaid", participle: "inlaid", translation: "інкрустувати, робити вставку" },
    { base: "input", past: "input / inputted", participle: "input / inputted", translation: "ввести, вводити (дані), вкладати (гроші)" },
    { base: "interbreed", past: "interbred", participle: "interbred", translation: "схрещувати" },
    { base: "interweave", past: "interwove / interweaved", participle: "interwoven / interweaved", translation: "заткати, вплітати, переплітати, змішувати" },
    { base: "interwind", past: "interwound", participle: "interwound", translation: "переплітати, перемотувати" },
    { base: "jerry-build", past: "jerry-built", participle: "jerry-built", translation: "будувати халтурно, нашвидкуруч" },
    { base: "keep", past: "kept", participle: "kept", translation: "тримати, зберігати, залишати" },
    { base: "kneel", past: "knelt / kneeled", participle: "knelt / kneeled", translation: "ставати на коліна, схиляти коліна" },
    { base: "knit", past: "knitted / knit", participle: "knitted / knit", translation: "в'язати, штопати" },
    { base: "know", past: "knew", participle: "known", translation: "знати, вміти, бути знайомим" },
    { base: "lay", past: "laid", participle: "laid", translation: "класти, валити, накривати" },
    { base: "lead", past: "led", participle: "led", translation: "вести, очолювати, супроводжувати" },
    { base: "lean", past: "leaned / leant", participle: "leaned / leant", translation: "спиратися, нахилятися, притулятися" },
    { base: "leap", past: "leaped / leapt", participle: "leaped / leapt", translation: "стрибати, скакати" },
    { base: "learn", past: "learned / learnt", participle: "learned / learnt", translation: "вчитися, дізнаватися" },
    { base: "leave", past: "left", participle: "left", translation: "залишати, кидати, лишити, піти їхати" },
    { base: "lend", past: "lent", participle: "lent", translation: "позичати, давати на час" },
    { base: "let", past: "let", participle: "let", translation: "дозволяти, допускати, випускати, проливати" },
    { base: "lie", past: "lay", participle: "lain", translation: "лежати, розташуватися, перебувати, знаходитися" },
    { base: "light", past: "lit / lighted", participle: "lit / lighted", translation: "світити, запалювати, світитися, опромінювати, натрапити, обрушитися" },
    { base: "lose", past: "lost", participle: "lost", translation: "втрачати, губити, позбавлятися, пропадати" },
    { base: "make", past: "made", participle: "made", translation: "робити, виробляти, здійснювати" },
    { base: "mean", past: "meant", participle: "meant", translation: "означати, мати на увазі" },
    { base: "meet", past: "met", participle: "met", translation: "зустрічати, знайомитися" },
    { base: "miscast", past: "miscast", participle: "miscast", translation: "неправильно розподіляти ролі" },
    { base: "misdeal", past: "misdealt", participle: "misdealt", translation: "чинити, поводитися неправильно, помилятися при здачі (карт)" },
    { base: "misdo", past: "misdid", participle: "misdone", translation: "робити неправильно, недбало, помилятися" },
    { base: "mishear", past: "misheard", participle: "misheard", translation: "недочути, погано почути" },
    { base: "mislay", past: "mislaid", participle: "mislaid", translation: "покласти не на місце, загубити" },
    { base: "mislead", past: "misled", participle: "misled", translation: "вводити в оману, обманювати, збивати зі шляху" },
    { base: "mislearn", past: "mislearned / mislearnt", participle: "mislearned / mislearnt", translation: "навчатися, вчити неправильно" },
    { base: "misread", past: "misread", participle: "misread", translation: "прочитати неправильно, неправильно тлумачити" },
    { base: "missay", past: "missaid", participle: "missaid", translation: "обмовитися, сказати неправильно" },
    { base: "misset", past: "misset", participle: "misset", translation: "неправильно встановити" },
    { base: "misspeak", past: "misspoke", participle: "misspoken", translation: "говорити, вимовляти неправильно" },
    { base: "misspell", past: "misspelled / misspelt", participle: "misspelled / misspelt", translation: "писати з помилками, робити орфографічні помилки" },
    { base: "misspend", past: "misspent", participle: "misspent", translation: "нерозумно, марно витрачати, розтринькати" },
    { base: "mistake", past: "mistook", participle: "mistaken", translation: "помилятися, помилитися у виборі" },
    { base: "misteach", past: "mistaught", participle: "mistaught", translation: "неправильно навчати" },
    { base: "misunderstand", past: "misunderstood", participle: "misunderstood", translation: "не розуміти, зрозуміти неправильно" },
    { base: "miswrite", past: "miswrote", participle: "miswritten", translation: "неправильно написати" },
    { base: "mow", past: "mowed", participle: "mowed / mown", translation: "косити, стригти (газон), жати" },
    { base: "offset", past: "offset", participle: "offset", translation: "відшкодовувати, компенсувати, відгалужуватися, відступати" },
    { base: "outbid", past: "outbid", participle: "outbid", translation: "перебивати ціну, перевершити, затьмарити" },
    { base: "outdo", past: "outdid", participle: "outdone", translation: "перевершити, вражати, побороти" },
    { base: "outdraw", past: "outdrew", participle: "outdrawn", translation: "домогтися більшої популярності, перевершити конкурентів" },
    { base: "outdrink", past: "outdrank", participle: "outdrunk", translation: "перепити (когось), випити більше, ніж хтось інший" },
    { base: "outdrive", past: "outdrove", participle: "outdriven", translation: "обігнати, випередити" },
    { base: "outfight", past: "outfought", participle: "outfought", translation: "мати перевагу над супротивником, перемагати" },
    { base: "outfly", past: "outflew", participle: "outflown", translation: "вилітати, літати швидше, далі (ніж будь-хто)" },
    { base: "outgrow", past: "outgrew", participle: "outgrown", translation: "випереджати в рості, переростати, позбавлятися з віком" },
    { base: "outleap", past: "outleaped / outleapt", participle: "outleaped / outleapt", translation: "перестрибувати, вистрибувати, стрибати краще" },
    { base: "outlie", past: "outlay", participle: "outlain", translation: "знаходитися назовні, поза чимось, жити в наметі" },
    { base: "outrun", past: "outran", participle: "outrun", translation: "випереджати, обігнати, втекти (від когось)" },
    { base: "outsell", past: "outsold", participle: "outsold", translation: "продавати дешевше інших" },
    { base: "outsleep", past: "outslept", participle: "outslept", translation: "проспати, заспатися" },
    { base: "outthink", past: "outthought", participle: "outthought", translation: "перевершувати у кмітливості, перехитрити, виявитися розумнішим" },
    { base: "outthrow", past: "outthrew", participle: "outthrown", translation: "викидати, виділяти; кидати краще, точніше" },
    { base: "outwear", past: "outwore", participle: "worn", translation: "зношувати, вичерпувати, служити довше, ніж (що-небудь)" },
    { base: "outwrite", past: "outwrote", participle: "outwritten", translation: "писати краще" },
    { base: "pay", past: "paid", participle: "paid", translation: "платити, винагороджувати" },
    { base: "plead", past: "pleaded / pled", participle: "pleaded / pled", translation: "захищати підсудного, клопотати, просити" },
    { base: "prebuild", past: "prebuilt", participle: "prebuilt", translation: "попередньо зібрати, вибудувати" },
    { base: "predo", past: "predid", participle: "predone", translation: "зробити заздалегідь, підготувати" },
    { base: "premake", past: "premade", participle: "premade", translation: "підготувати, зробити наперед, заздалегідь" },
    { base: "prepay", past: "prepaid", participle: "prepaid", translation: "передплачувати, платити наперед" },
    { base: "presell", past: "presold", participle: "presold", translation: "рекламувати продукт до його появи в продажу, продавати наперед" },
    { base: "preshrink", past: "preshrunk", participle: "preshrunk", translation: "обробляти тканину для запобігання її стяжки" },
    { base: "prove", past: "proved", participle: "proven", translation: "доводити, засвідчувати" },
    { base: "put", past: "put", participle: "put", translation: "класти, покласти" },
    { base: "quick-freeze", past: "quick-froze", participle: "quick-frozen", translation: "швидко заморожувати, замерзати" },
    { base: "quit", past: "quit / quitted", participle: "quit / quitted", translation: "залишати, покидати, виходити" },
    { base: "read", past: "read [red]", participle: "read [red]", translation: "читати" },
    { base: "reawake", past: "reawoke", participle: "reawaken", translation: "знову будити" },
    { base: "rebid", past: "rebid", participle: "rebid", translation: "робити повторну ставку" },
    { base: "rebind", past: "rebound", participle: "rebound", translation: "знову переплітати (книгу), робити нову палітурку" },
    { base: "rebroadcast", past: "rebroadcast / rebroadcasted", participle: "rebroadcast / rebroadcasted", translation: "ретранслювати, знову показувати (передачу)" },
    { base: "rebuild", past: "rebuilt", participle: "rebuilt", translation: "перебудовувати" },
    { base: "recast", past: "recast", participle: "recast", translation: "переробляти, змінювати, перераховувати" },
    { base: "recut", past: "recut", participle: "recut", translation: "вдруге нарізати, повторно вирізати (сцени з фільму)" },
    { base: "redeal", past: "redealt", participle: "redealt", translation: "роздати знову карти в грі" },
    { base: "redo", past: "redid", participle: "redone", translation: "переробляти, робити ремонт" },
    { base: "redraw", past: "redrew", participle: "redrawn", translation: "перемальовувати, оновлювати малюнок, виставляти зворотний вексель" },
    { base: "refit", past: "refitted / refit", participle: "refitted / refit", translation: "переустатковувати, лагодити, знову підганяти (за розміром)" },
    { base: "regrind", past: "reground", participle: "reground", translation: "перешліфовувати, переточувати, притирати" },
    { base: "regrow", past: "regrew", participle: "regrown", translation: "відростати знову" },
    { base: "rehang", past: "rehung", participle: "rehung", translation: "переважувати" },
    { base: "rehear", past: "reheard", participle: "reheard", translation: "почути знову, розглядати справу повторно" },
    { base: "reknit", past: "reknitted / reknit", participle: "reknitted / reknit", translation: "в'язати заново, з'єднувати заново" },
    { base: "relay", past: "relayed", participle: "relayed", translation: "передавати, пересилати" },
    { base: "remake", past: "remade", participle: "remade", translation: "переробляти, робити заново" },
    { base: "rend", past: "rent / rended", participle: "rent / rended", translation: "відривати, роздирати, розщеплювати" },
    { base: "repay", past: "repaid", participle: "repaid", translation: "віддавати, повертати, відшкодовувати, відплачувати" },
    { base: "reread", past: "reread", participle: "reread", translation: "перечитувати" },
    { base: "rerun", past: "reran", participle: "rerun", translation: "перезапускати, повторно проводити, показувати" },
    { base: "resell", past: "resold", participle: "resold", translation: "перепродавати" },
    { base: "reset", past: "reset", participle: "reset", translation: "знову налаштовувати, встановлювати, скидати (налаштування)" },
    { base: "resew", past: "resewed", participle: "resewn / resewed", translation: "пришивати заново, перешивати" },
    { base: "retake", past: "retook", participle: "retaken", translation: "знову взяти, перезнімати, перездавати (іспит)" },
    { base: "reteach", past: "retaught", participle: "retaught", translation: "переучувати, вчити заново" },
    { base: "retread", past: "retread", participle: "retread", translation: "змінити покришку, перенавчати" },
    { base: "rewake", past: "rewoke / rewaked", participle: "rewaken / rewaked", translation: "будити, пробуджуватися заново" },
    { base: "rewear", past: "rewore", participle: "reworn", translation: "носити заново" },
    { base: "reweave", past: "rewove / reweaved", participle: "rewoven / reweaved", translation: "переткати, плести, ткати заново, знову з'єднуватися" },
    { base: "rid", past: "rid", participle: "rid", translation: "звільняти, рятувати" },
    { base: "ride", past: "rode", participle: "ridden", translation: "їхати верхи, кататися, їхати (в транспорті)" },
    { base: "ring", past: "rang", participle: "rung", translation: "дзвонити, дзвеніти" },
    { base: "rise", past: "rose", participle: "risen", translation: "підніматися, сходити" },
    { base: "run", past: "ran", participle: "run", translation: "бігти, гнати, управляти, текти" },
    { base: "saw", past: "sawed", participle: "sawed / sawn", translation: "пиляти, розпиляти" },
    { base: "say", past: "said", participle: "said", translation: "говорити, сказати" },
    { base: "see", past: "saw", participle: "seen", translation: "бачити, дивитися" },
    { base: "seek", past: "sought", participle: "sought", translation: "шукати, домагатися" },
    { base: "sell", past: "sold", participle: "sold", translation: "продавати" },
    { base: "send", past: "sent", participle: "sent", translation: "посилати, відправляти" },
    { base: "set", past: "set", participle: "set", translation: "поміщати, ставити" },
    { base: "sew", past: "sewed", participle: "sewn / sewed", translation: "шити, штопати" },
    { base: "shake", past: "shook", participle: "shaken", translation: "трясти, струшувати" },
    { base: "shave", past: "shaved", participle: "shaved / shaven", translation: "голитися" },
    { base: "shear", past: "sheared", participle: "sheared / shorn", translation: "різати, вистригати, розсікати" },
    { base: "shed", past: "shed", participle: "shed", translation: "проливати, втрачати, скидати" },
    { base: "shine", past: "shined / shone", participle: "shined / shone", translation: "сяяти, світити" },
    { base: "shit", past: "shit / shat / shitted", participle: "shit / shat / shitted", translation: "какати, гадити" },
    { base: "shoe", past: "shod", participle: "shod", translation: "взувати, підкувати" },
    { base: "shoot", past: "shot", participle: "shot", translation: "стріляти, полювати" },
    { base: "show", past: "showed", participle: "shown / showed", translation: "показувати" },
    { base: "shrink", past: "shrank / shrunk", participle: "shrunk / shrunken", translation: "сідати, давати усадку, стискатися" },
    { base: "shut", past: "shut", participle: "shut", translation: "закривати" },
    { base: "sight-read", past: "sight-read", participle: "sight-read", translation: "грати, співати з листа, читати ноти, текст з листа" },
    { base: "sing", past: "sang", participle: "sung", translation: "співати" },
    { base: "sink", past: "sank / sunk", participle: "sunk", translation: "тонути, опускатися, занурюватися" },
    { base: "sit", past: "sat", participle: "sat", translation: "сидіти, садити, перебувати" },
    { base: "slay", past: "slew / slayed", participle: "slain / slayed", translation: "вбивати, знищувати" },
    { base: "sleep", past: "slept", participle: "slept", translation: "спати" },
    { base: "slide", past: "slid", participle: "slid", translation: "ковзати, повзати, кататися" },
    { base: "sling", past: "slung", participle: "slung", translation: "жбурляти, вішати через плече" },
    { base: "slink", past: "slinked / slunk", participle: "slinked / slunk", translation: "крастися, підкрадатися" },
    { base: "slit", past: "slit", participle: "slit", translation: "розрізати, перерізати" },
    { base: "smell", past: "smelled / smelt", participle: "smelled / smelt", translation: "пахнути, нюхати" },
    { base: "smite", past: "smote", participle: "smitten", translation: "вражати, бити" },
    { base: "sneak", past: "sneaked / snuck", participle: "sneaked / snuck", translation: "крастися, підкрадатися" },
    { base: "sow", past: "sowed", participle: "sown / sowed", translation: "сіяти, засівати" },
    { base: "speak", past: "spoke", participle: "spoken", translation: "говорити" },
    { base: "speed", past: "sped / speeded", participle: "sped / speeded", translation: "поспішати, прискорювати" },
    { base: "spell", past: "spelled / spelt", participle: "spelled / spelt", translation: "замовляти, зачаровувати" },
    { base: "spend", past: "spent", participle: "spent", translation: "витрачати" },
    { base: "spill", past: "spilled / spilt", participle: "spilled / spilt", translation: "проливати, розливатися" },
    { base: "spin", past: "spun", participle: "spun", translation: "прясти, крутити" },
    { base: "spit", past: "spit / spat", participle: "spit / spat", translation: "плювати" },
    { base: "spoil", past: "spoiled / spoilt", participle: "spoiled / spoilt", translation: "псувати, балувати" },
    { base: "spread", past: "spread", participle: "spread", translation: "поширюватися, розстеляти" },
    { base: "spring", past: "sprang / sprung", participle: "sprung", translation: "стрибати, вскочити" },
    { base: "stand", past: "stood", participle: "stood", translation: "стояти, бути розташованим" },
    { base: "stave", past: "staved / stove", participle: "staved / stove", translation: "пробивати, розбивати" },
    { base: "steal", past: "stole", participle: "stolen", translation: "красти, викрадати" },
    { base: "stick", past: "stuck", participle: "stuck", translation: "встромляти, колоти, приклеювати" },
    { base: "sting", past: "stung", participle: "stung", translation: "жалити, заподіювати біль" },
    { base: "stink", past: "stank / stunk", participle: "stunk", translation: "смердіти, погано пахнути" },
    { base: "strew", past: "strewed", participle: "strewn / strewed", translation: "усіяти, розкидати" },
    { base: "stride", past: "strode", participle: "stridden", translation: "крокувати" },
    { base: "strike", past: "struck", participle: "struck / stricken", translation: "ударяти, вражати" },
    { base: "string", past: "strung", participle: "strung", translation: "пов'язувати, натягувати" },
    { base: "strive", past: "strove / strived", participle: "striven / strived", translation: "прагнути, намагатися" },
    { base: "sublet", past: "sublet", participle: "sublet", translation: "передавати в суборенду" },
    { base: "sunburn", past: "sunburned / sunburnt", participle: "sunburned / sunburnt", translation: "обгорати на сонці" },
    { base: "swear", past: "swore", participle: "sworn", translation: "клястися, присягати" },
    { base: "sweat", past: "sweat / sweated", participle: "sweat / sweated", translation: "потіти" },
    { base: "sweep", past: "swept", participle: "swept", translation: "мести, прочищати" },
    { base: "swell", past: "swelled", participle: "swollen / swelled", translation: "пухнути, роздуватися" },
    { base: "swim", past: "swam", participle: "swum", translation: "плавати" },
    { base: "swing", past: "swung", participle: "swung", translation: "качати, хитатися" },
    { base: "take", past: "took", participle: "taken", translation: "брати" },
    { base: "teach", past: "taught", participle: "taught", translation: "навчати" },
    { base: "tear", past: "tore", participle: "torn", translation: "рвати" },
    { base: "telecast", past: "telecast", participle: "telecast", translation: "передавати по телебаченню" },
    { base: "tell", past: "told", participle: "told", translation: "говорити, розповідати" },
    { base: "test-drive", past: "test-drove", participle: "test-driven", translation: "робити пробну поїздку" },
    { base: "test-fly", past: "test-flew", participle: "test-flown", translation: "випробовувати в літніх умовах (літак)" },
    { base: "think", past: "thought", participle: "thought", translation: "думати" },
    { base: "thrive", past: "throve / thrived", participle: "thrived / thriven", translation: "процвітати" },
    { base: "throw", past: "threw", participle: "thrown", translation: "кидати" },
    { base: "thrust", past: "thrust", participle: "thrust", translation: "колоти, штовхати" },
    { base: "tread", past: "trod", participle: "trodden / trod", translation: "йти, ступати" },
    { base: "typecast", past: "typecast", participle: "typecast", translation: "підбирати акторів по типажності" },
    { base: "typeset", past: "typeset", participle: "typeset", translation: "набирати текст для друку" },
    { base: "typewrite", past: "typewrote", participle: "typewritten", translation: "друкувати на друкарській машинці" },
    { base: "unbend", past: "unbent", participle: "unbent", translation: "розгинатися" },
    { base: "unbind", past: "unbound", participle: "unbound", translation: "розв'язати" },
    { base: "unclothe", past: "unclothed / unclad", participle: "unclothed / unclad", translation: "роздягати" },
    { base: "underbid", past: "underbid", participle: "underbid", translation: "перебивати ціну" },
    { base: "undercut", past: "undercut", participle: "undercut", translation: "підрізати" },
    { base: "underfeed", past: "underfed", participle: "underfed", translation: "недогодовувати" },
    { base: "undergo", past: "underwent", participle: "undergone", translation: "відчувати, переносити" },
    { base: "underlie", past: "underlay", participle: "underlain", translation: "підкреслювати, виділяти" },
    { base: "undersell", past: "undersold", participle: "undersold", translation: "продавати дешевше інших" },
    { base: "underspend", past: "underspent", participle: "underspent", translation: "витрачати недостатньо" },
    { base: "understand", past: "understood", participle: "understood", translation: "розуміти" },
    { base: "undertake", past: "undertook", participle: "undertaken", translation: "робити, гарантувати" },
    { base: "underwrite", past: "underwrote", participle: "underwritten", translation: "підписувати, гарантувати" },
    { base: "undo", past: "undid", participle: "undone", translation: "розстібати, скасовувати" },
    { base: "unfreeze", past: "unfroze", participle: "unfrozen", translation: "розморозити" },
    { base: "unhang", past: "unhung", participle: "unhung", translation: "знімати (щось, що висить)" },
    { base: "unhide", past: "unhid", participle: "unhidden", translation: "показувати приховані елементи" },
    { base: "unknit", past: "unknitted / unknit", participle: "unknitted / unknit", translation: "розпускати (в'язання)" },
    { base: "unlearn", past: "unlearned / unlearnt", participle: "unlearned / unlearnt", translation: "розучитися" },
    { base: "unsew", past: "unsewed", participle: "unsewn / unsewed", translation: "розпорювати" },
    { base: "unsling", past: "unslung", participle: "unslung", translation: "знімати, звільнити від ременя" },
    { base: "unspin", past: "unspun", participle: "unspun", translation: "розпускати, розплітати" },
    { base: "unstick", past: "unstuck", participle: "unstuck", translation: "віддирати, відклеювати" },
    { base: "unstring", past: "unstrung", participle: "unstrung", translation: "знімати, послаблювати" },
    { base: "unweave", past: "unwove / unweaved", participle: "unwoven / unweaved", translation: "розпускати, розплітати (тканину)" },
    { base: "unwind", past: "unwound", participle: "unwound", translation: "розкручувати, розвивати" },
    { base: "uphold", past: "upheld", participle: "upheld", translation: "підтримувати" },
    { base: "upset", past: "upset", participle: "upset", translation: "перекидати, засмучувати" },
    { base: "wake", past: "woke / waked", participle: "woken / waked", translation: "будити" },
    { base: "waylay", past: "waylaid", participle: "waylaid", translation: "підстерігати" },
    { base: "wear", past: "wore", participle: "worn", translation: "носити одяг" },
    { base: "weave", past: "wove / weaved", participle: "woven / weaved", translation: "ткати, плести" },
    { base: "wed", past: "wed / wedded", participle: "wed / wedded", translation: "вінчати, одружуватися" },
    { base: "weep", past: "wept", participle: "wept", translation: "плакати" },
    { base: "wet", past: "wet / wetted", participle: "wet / wetted", translation: "мочити" },
    { base: "win", past: "won", participle: "won", translation: "вигравати" },
    { base: "wind", past: "wound", participle: "wound", translation: "чуяти, дути, намотувати" },
    { base: "withdraw", past: "withdrew", participle: "withdrawn", translation: "брати назад" },
    { base: "withhold", past: "withheld", participle: "withheld", translation: "утримуватися" },
    { base: "withstand", past: "withstood", participle: "withstood", translation: "встояти" },
    { base: "wring", past: "wrung", participle: "wrung", translation: "викручувати" },
    { base: "write", past: "wrote", participle: "written", translation: "писати" }
];
let tableBody = document.getElementById("verbs-table");

function renderTable(data) {
    tableBody.innerHTML = "";
    data.forEach(verb => {
        let row = document.createElement("tr");
        row.innerHTML = `<td>${verb.base}</td><td>${verb.past}</td><td>${verb.participle}</td><td>${verb.translation}</td>`;
        tableBody.appendChild(row);
    });
}

function filterVerbs() {
    let searchTerm = document.getElementById("search").value.toLowerCase();
    let filteredVerbs = verbs.filter(verb => 
        verb.base.toLowerCase().includes(searchTerm) ||
        verb.past.toLowerCase().includes(searchTerm) ||
        verb.participle.toLowerCase().includes(searchTerm)
    );
    renderTable(filteredVerbs);
}

renderTable(verbs);

